### ISSUE TITLE
v0.1.0-rc.39 keeps failing with with "Unexpected value 'action'" error

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo-render-action#5]
We upgraded to latest action version and it keeps failing with the  "Unexpected value 'action'" error

<img width="1237" alt="image" src="https://github.com/akuity/kargo-render-action/assets/426437/90d7efea-cca0-4a39-bced-b0aa361a534b">

**Comment by blakepettersson** [comment]
Fixed by #6
